{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "timeoff.fullname" . }}
spec:
  rules:
  - host:  {{ .Values.ingress.subdomain }}.{{ .Values.global.timeoff.environment.ingressDomain }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "timeoff.fullname" . }}
            port:
              number: {{ .Values.service.port  }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.subdomain }}.{{ .Values.global.timeoff.environment.ingressDomain }}
    secretName: {{ include "timeoff.fullname" . }}-tls
{{- end }}
